name: Pull Request Labeler

on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    if: github.actor != 'discourse-translator-bot'
    runs-on: debian-12

    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
